name: "Rails Test Image"

on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          #might not need line below
          file: ./DockerfileRailsLive
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/rails-production-test
        
        
