name: docker react test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get Current Date
        run: echo ::set-output name=date::$(date +%Y%m%d%H%M)
        id: date

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./DockerfileReactLive
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/react-production-test
            ${{ secrets.DOCKERHUB_USERNAME }}/react-production-test:${{ steps.date.outputs.date }}
