name: docker react test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"
      - name: Installing dependencies
        run: npm ci
      - name: Building project
        run: npm run build

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Build
        uses: docker/setup-build-action@v2

      - name: Get Current Date
        run: echo ::set-output name=date::$(date +%Y%m%d%H%M)
        id: date

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          # these images are in dockerhub and we are trying to remote add the files into the EC2 instance
          context: .
          file: ./Dockerfile
          push: true
          # by the way, steps.<step_id>.outputs.<output_name> utilizes the id: date you declared earlier within 'Get Current Date'
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/react-production-test
            ${{ secrets.DOCKERHUB_USERNAME }}/react-production-test:${{ steps.date.outputs.date }}